version: '3'
services:
 zookeeper:
   image: confluentinc/cp-zookeeper:5.3.1
   hostname: zookeeper
   container_name: zookeeper
   ports:
     - "2181:2181"
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
 
 broker:
   image: confluentinc/cp-kafka:5.3.1
   hostname: broker
   container_name: broker
   depends_on:
     - zookeeper
   ports:
     - "9092:9092"
     - "9093:9093"
   environment:
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:19092,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_BROKER_ID: 1
     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
 
 schema-registry:
   image: confluentinc/cp-schema-registry:5.3.1
   hostname: schema-registry
   container_name: schema-registry
   depends_on:
     - zookeeper
     - broker
   ports:
     - "8881:8081"
   environment:
     SCHEMA_REGISTRY_HOST_NAME: schema-registry
     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
 
